# Site settings for local

title: Local

collections:
  diary:
    output: true
  micro_posts:
    output: true
  notes:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - README.md

header_pages:
  - notes.html
  - docs.html
  - diary.html
  - micro_posts.html
  - about.md
