# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shunfa's Blog
description: > # this means to ignore newlines until "baseurl:"
  Make products people love.
url: "https://goooooouwa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - README.md

# Build settings
markdown: kramdown

# Theme settings for minima

theme: minima

author:
  name: Shunfa Xu
  email: gouwa5700 (at) gmail (dot) com

minima:
  social_links:
    twitter: Goooooouwa
    github: goooooouwa
    linkedin: gregxu

show_excerpts: false

# Plugin settings

pagination:
  enabled: true
  per_page: 15
  sort_reverse: true

jekyll-archives:
  enabled:
    - year
    - categories
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    category: '/category/:name/'