# Site settings for https://goooooouwa.github.io/blog
title: Shunfa's Notes
baseurl: "/blog" # the subpath of your site, e.g. /blog

disqus:
  shortname: goooooouwa

google_analytics: UA-137406515-2

google_custom_engine: 001725026263712877590:9lrhbwyoknb

header_pages:
  - about.md
  - notes.html

collections:
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
  - diary.html
