# Site settings for https://goooooouwa.github.io/resume
title: A Product Guy
baseurl: "/resume" # the subpath of your site, e.g. /blog

header_pages:
  - about.md

google_analytics: UA-137406515-1

google_custom_engine: 001725026263712877590:cfivcwakujs

exclude:
  - notes.html