# local development settings

title: Local

header_pages:
  - notes.html
  - diary.html

collections:
  diary:
    output: true
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "diary"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

jekyll_compose:
  auto_open: true

# remote_theme: pages-themes/merlot