# Site settings for https://goooooouwa.github.io/blog
title: My Blog
baseurl: "/blog" # the subpath of your site, e.g. /blog

disqus:
  shortname: goooooouwa

github_username:  goooooouwa
twitter_username: Goooooouwa

jekyll-archives:
  enabled:
    - year
    - categories
    - tags
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

header_pages:
  - docs/about.md
  - category/business.html
  - category/cars.html
  - category/coding.html
  - category/product.html
  - rails.html
  - ruby.html
  - linux.html

collections_dir: docs
collections:
  business:
    output: true
  business_analysis:
    output: true
  cars:
    output: true
  coding:
    output: true
  computer:
    output: true
  design:
    output: true
  gaming:
    output: true
  housing:
    output: true
  linux:
    output: true
  music:
    output: true
  personal:
    output: true
  product_management:
    output: true
  productivity:
    output: true
  racing:
    output: true
  rails:
    output: true
  ruby:
    output: true
  user_research:
    output: true

defaults:
  - scope:
      path: ""
      type: "rails"
    values:
      layout: "doc"
  - scope:
      path: ""
      type: "ruby"
    values:
      layout: "doc"
  - scope:
      path: ""
      type: "linux"
    values:
      layout: "doc"

google_analytics: UA-137406515-2

google_custom_engine: 001725026263712877590:9lrhbwyoknb
