# Site settings for https://goooooouwa.github.io/blog
title: Shunfa's Notes
baseurl: "/blog" # the subpath of your site, e.g. /blog

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  notes:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - README.md
  - diary.html

# Theme settings for minima

minima:
  skin: dark

disqus:
  shortname: goooooouwa

google_analytics: UA-137406515-2

header_pages:
  - about.md
  - notes.html

# Plugin settings

google_custom_engine: 001725026263712877590:9lrhbwyoknb
