# Site settings for https://goooooouwa.github.io/

github_username:  goooooouwa
twitter_username: Goooooouwa

header_pages:
    - about.md
    - category/business.html
    - category/coding.html
    - category/product.html
