# Site settings for local

title: Local

collections:
  diary:
    output: true
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "diary"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Theme settings for minima

minima:
  skin: solarized-dark

header_pages:
  - notes.html
  - diary.html
  - about.md

# Plugin settings

jekyll_compose:
  auto_open: true
