# Site settings for https://goooooouwa.github.io/me

disqus:
  shortname: goooooouwa

github_username:  goooooouwa
twitter_username: Goooooouwa

google_analytics: UA-137406515-1

google_custom_engine: 001725026263712877590:cfivcwakujs
