# Site settings for https://goooooouwa.github.io/cv
title: A Product Guy
baseurl: "/cv" # the subpath of your site, e.g. /blog

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - README.md
  - notes.html
  - diary.html

# Theme settings for minima

minima:
  skin: solarized

google_analytics: UA-137406515-1

header_pages:
  - about.md

# Plugin settings

google_custom_engine: 001725026263712877590:cfivcwakujs
