# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shunfa's Blog
email: gouwa5700 (at) gmail (dot) com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goooooouwa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Shunfa Xu
show_excerpts: false

disqus:
  shortname: goooooouwa

github_username:  goooooouwa
twitter_username: Goooooouwa

google_analytics: UA-137406515-1

google_custom_engine: 001725026263712877590:cfivcwakujs

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true

jekyll_compose:
  auto_open: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

header_pages:
  - about.md
  - category/business.html
  - category/coding.html
  - category/product.html

jekyll-archives:
  enabled:
    - year
    - categories
    - tags
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
