# Site settings for https://goooooouwa.github.io/blog
title: Shunfa's Blog
baseurl: "" # the subpath of your site, e.g. /blog

collections:
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - README.md
  - diary.html

# Theme settings for minima

minima:
  skin: solarized

disqus:
  shortname: goooooouwa

google_analytics: UA-137406515-2

header_pages:
  - notes.html
  - docs.html
  - about.md

# Plugin settings

google_custom_engine: 001725026263712877590:9lrhbwyoknb
