# Site settings for https://goooooouwa.github.io/blog
title: Shunfa's Notes
baseurl: "/blog" # the subpath of your site, e.g. /blog

disqus:
  shortname: goooooouwa

header_pages:
  - about.md
  - notes.html

collections:
  notes:
    output: true

defaults:
  - scope:
        path: ""
        type: "notes"
      values:
        layout: "doc"

google_analytics: UA-137406515-2

google_custom_engine: 001725026263712877590:9lrhbwyoknb
