# Site settings for https://goooooouwa.github.io/resume
title: A Product Guy
baseurl: "/resume" # the subpath of your site, e.g. /blog

github_username:  goooooouwa
twitter_username: Goooooouwa

jekyll-archives:
    enabled:
      - year
      - categories
      - tags
    layout: archive
    permalinks:
      year: '/:year/'
      month: '/:year/:month/'
      day: '/:year/:month/:day/'
      tag: '/tag/:name/'
      category: '/category/:name/'

header_pages:
    - pages/about.md
    - category/business.html
    - category/coding.html
    - category/product.html

google_analytics: UA-137406515-1

google_custom_engine: 001725026263712877590:cfivcwakujs
